spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
    show-sql: false
  flyway:
    enabled: true
    baseline-on-migrate: true

upload:
  dir: ${UPLOAD_DIR:/var/freelance/uploads}
